# Generated by Django 2.2.4 on 2021-02-23 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app_authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.CharField(default='no value', max_length=500),
            preserve_default=False,
        ),
    ]
