# Generated by Django 2.2.4 on 2021-02-25 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app_login', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserManager',
        ),
    ]
