# Generated by Django 2.2.4 on 2021-02-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app_tvshows', '0003_remove_show_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='release_date',
            field=models.DateField(default='no value'),
            preserve_default=False,
        ),
    ]
