# Generated by Django 2.2.4 on 2021-02-24 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app_tvshows', '0004_show_release_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='release_date',
            new_name='release_date1',
        ),
    ]
