# Generated by Django 2.2.4 on 2021-02-20 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app_dojo_ninja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='city',
            field=models.CharField(default='non value', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dojo',
            name='state',
            field=models.CharField(default='no value', max_length=255),
            preserve_default=False,
        ),
    ]
