# Generated by Django 2.2.4 on 2021-03-03 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_marcela', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
